//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATCQUIZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int ID { get; set; }
        public string QuestionText { get; set; }
        public string Type { get; set; }
        public string Source { get; set; }
        public bool isDeleted { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> GivenAnswers { get; set; }
        public Nullable<int> CorrectAnswers { get; set; }
    }
}
